// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzw0WM4U3-uortVEh09TCcyaNXGHKtazY',
    appId: '1:137253980627:web:c7070d685e744a85318726',
    messagingSenderId: '137253980627',
    projectId: 'sfuverce-app-5c38d',
    authDomain: 'sfuverce-app-5c38d.firebaseapp.com',
    storageBucket: 'sfuverce-app-5c38d.appspot.com',
    measurementId: 'G-KN1MGW1FFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQK5gR0aNMrSiFv1OTGPvwL9YnlL_JHis',
    appId: '1:137253980627:android:7ef6cc21ad1954b0318726',
    messagingSenderId: '137253980627',
    projectId: 'sfuverce-app-5c38d',
    storageBucket: 'sfuverce-app-5c38d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFb7MCMekIPysXMb3cUdzGCvvrjpQ6r2s',
    appId: '1:137253980627:ios:e45fe7ec0dade8d8318726',
    messagingSenderId: '137253980627',
    projectId: 'sfuverce-app-5c38d',
    storageBucket: 'sfuverce-app-5c38d.appspot.com',
    iosClientId: '137253980627-cjisr5pnc12gjhtd1oqradiafup2g8ol.apps.googleusercontent.com',
    iosBundleId: 'com.example.sfuverceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFb7MCMekIPysXMb3cUdzGCvvrjpQ6r2s',
    appId: '1:137253980627:ios:e45fe7ec0dade8d8318726',
    messagingSenderId: '137253980627',
    projectId: 'sfuverce-app-5c38d',
    storageBucket: 'sfuverce-app-5c38d.appspot.com',
    iosClientId: '137253980627-cjisr5pnc12gjhtd1oqradiafup2g8ol.apps.googleusercontent.com',
    iosBundleId: 'com.example.sfuverceApp',
  );
}
